-- ============================================================
-- LONGSANG AI COMPANY — Agent Registry System
-- Migration: 20260225_agent_registry.sql
-- Purpose: Create unified agent tracking (agent = virtual employee)
-- DB: Shared Supabase (diexsbzqwsbpilsymnfb)
-- ============================================================

-- 1. Agent Registry (master list of all AI agents)
CREATE TABLE IF NOT EXISTS agent_registry (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Identity
  name TEXT NOT NULL,
  codename TEXT UNIQUE NOT NULL,
  department TEXT NOT NULL,
  avatar_emoji TEXT DEFAULT '🤖',
  description TEXT,
  
  -- Classification
  type TEXT NOT NULL CHECK (type IN ('pipeline', 'autonomous', 'on-demand', 'scheduled', 'reactive')),
  source_project TEXT,          -- "youtube-agent-crew", "long-sang-forge", "agentkits-marketing", etc.
  source_file TEXT,             -- relative path to agent code
  
  -- Capability
  model TEXT DEFAULT 'gemini-2.0-flash',
  tools JSONB DEFAULT '[]',
  skills JSONB DEFAULT '[]',
  
  -- Employment
  status TEXT DEFAULT 'idle' CHECK (status IN ('active', 'idle', 'busy', 'error', 'disabled', 'training')),
  hired_at TIMESTAMPTZ DEFAULT now(),
  last_active_at TIMESTAMPTZ,
  
  -- Performance KPI
  total_executions INTEGER DEFAULT 0,
  success_count INTEGER DEFAULT 0,
  fail_count INTEGER DEFAULT 0,
  success_rate NUMERIC(5,2) DEFAULT 100.00,
  avg_execution_time_ms INTEGER DEFAULT 0,
  total_cost_usd NUMERIC(10,4) DEFAULT 0,
  total_revenue_usd NUMERIC(10,4) DEFAULT 0,
  quality_score NUMERIC(3,2) DEFAULT 5.00,
  
  -- Config
  schedule TEXT,                -- cron expression
  config JSONB DEFAULT '{}',
  cost_per_run NUMERIC(10,6) DEFAULT 0,
  
  -- Organization
  reports_to UUID REFERENCES agent_registry(id),
  company_id UUID,             -- SABOHUB company link
  
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Agent Execution Log
CREATE TABLE IF NOT EXISTS agent_execution_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID REFERENCES agent_registry(id) NOT NULL,
  
  -- Execution
  trigger_type TEXT NOT NULL DEFAULT 'manual',  -- "cron", "manual", "pipeline", "webhook", "realtime"
  input JSONB,
  output JSONB,
  status TEXT DEFAULT 'running' CHECK (status IN ('running', 'success', 'failed', 'timeout', 'cancelled')),
  error_message TEXT,
  
  -- Metrics
  started_at TIMESTAMPTZ DEFAULT now(),
  completed_at TIMESTAMPTZ,
  duration_ms INTEGER,
  cost_usd NUMERIC(10,6) DEFAULT 0,
  tokens_used INTEGER DEFAULT 0,
  
  -- Context
  pipeline_id TEXT,
  stage_number INTEGER,
  parent_execution_id UUID REFERENCES agent_execution_log(id),
  
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Agent Daily Report (generated by pg_cron at 11 PM)
CREATE TABLE IF NOT EXISTS agent_daily_report (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID REFERENCES agent_registry(id) NOT NULL,
  report_date DATE DEFAULT CURRENT_DATE,
  
  executions_count INTEGER DEFAULT 0,
  success_count INTEGER DEFAULT 0,
  fail_count INTEGER DEFAULT 0,
  total_cost_usd NUMERIC(10,4) DEFAULT 0,
  total_revenue_usd NUMERIC(10,4) DEFAULT 0,
  avg_quality_score NUMERIC(3,2),
  
  highlights JSONB DEFAULT '[]',
  issues JSONB DEFAULT '[]',
  kpi_data JSONB DEFAULT '{}',
  
  UNIQUE(agent_id, report_date),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Agent Messages (agent-to-agent or CEO-to-agent communication)
CREATE TABLE IF NOT EXISTS agent_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  from_agent_id UUID REFERENCES agent_registry(id),
  to_agent_id UUID REFERENCES agent_registry(id),
  from_user_id UUID,          -- if from CEO
  
  message_type TEXT DEFAULT 'task' CHECK (message_type IN ('task', 'report', 'alert', 'handoff', 'question', 'decision')),
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_agent_department ON agent_registry(department);
CREATE INDEX IF NOT EXISTS idx_agent_status ON agent_registry(status);
CREATE INDEX IF NOT EXISTS idx_agent_type ON agent_registry(type);
CREATE INDEX IF NOT EXISTS idx_exec_agent ON agent_execution_log(agent_id);
CREATE INDEX IF NOT EXISTS idx_exec_status ON agent_execution_log(status);
CREATE INDEX IF NOT EXISTS idx_exec_date ON agent_execution_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_daily_agent_date ON agent_daily_report(agent_id, report_date DESC);
CREATE INDEX IF NOT EXISTS idx_msg_to ON agent_messages(to_agent_id, created_at DESC);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_agent_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_registry_updated_at
  BEFORE UPDATE ON agent_registry
  FOR EACH ROW
  EXECUTE FUNCTION update_agent_updated_at();

-- Function: Update agent KPI after execution
CREATE OR REPLACE FUNCTION update_agent_kpi()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status IN ('success', 'failed') AND NEW.completed_at IS NOT NULL THEN
    UPDATE agent_registry SET
      total_executions = total_executions + 1,
      success_count = success_count + CASE WHEN NEW.status = 'success' THEN 1 ELSE 0 END,
      fail_count = fail_count + CASE WHEN NEW.status = 'failed' THEN 1 ELSE 0 END,
      success_rate = ROUND(
        (success_count + CASE WHEN NEW.status = 'success' THEN 1 ELSE 0 END)::NUMERIC /
        NULLIF(total_executions + 1, 0) * 100, 2
      ),
      avg_execution_time_ms = CASE
        WHEN total_executions = 0 THEN COALESCE(NEW.duration_ms, 0)
        ELSE ROUND((avg_execution_time_ms * total_executions + COALESCE(NEW.duration_ms, 0))::NUMERIC / (total_executions + 1))
      END,
      total_cost_usd = total_cost_usd + COALESCE(NEW.cost_usd, 0),
      last_active_at = NEW.completed_at,
      status = 'idle'
    WHERE id = NEW.agent_id;
  ELSIF NEW.status = 'running' THEN
    UPDATE agent_registry SET status = 'busy', last_active_at = now()
    WHERE id = NEW.agent_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_execution_kpi_update
  AFTER INSERT OR UPDATE ON agent_execution_log
  FOR EACH ROW
  EXECUTE FUNCTION update_agent_kpi();

-- Function: Generate daily report (called by pg_cron at 23:00)
CREATE OR REPLACE FUNCTION generate_agent_daily_reports()
RETURNS void AS $$
BEGIN
  INSERT INTO agent_daily_report (agent_id, report_date, executions_count, success_count, fail_count, total_cost_usd)
  SELECT
    agent_id,
    CURRENT_DATE,
    COUNT(*),
    COUNT(*) FILTER (WHERE status = 'success'),
    COUNT(*) FILTER (WHERE status = 'failed'),
    COALESCE(SUM(cost_usd), 0)
  FROM agent_execution_log
  WHERE created_at >= CURRENT_DATE
    AND created_at < CURRENT_DATE + INTERVAL '1 day'
    AND status IN ('success', 'failed')
  GROUP BY agent_id
  ON CONFLICT (agent_id, report_date)
  DO UPDATE SET
    executions_count = EXCLUDED.executions_count,
    success_count = EXCLUDED.success_count,
    fail_count = EXCLUDED.fail_count,
    total_cost_usd = EXCLUDED.total_cost_usd;
END;
$$ LANGUAGE plpgsql;

-- Enable Realtime for agent monitoring
ALTER PUBLICATION supabase_realtime ADD TABLE agent_registry;
ALTER PUBLICATION supabase_realtime ADD TABLE agent_execution_log;
ALTER PUBLICATION supabase_realtime ADD TABLE agent_messages;

-- RLS Policies (Admin can do everything, public can read)
ALTER TABLE agent_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_execution_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_daily_report ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_messages ENABLE ROW LEVEL SECURITY;

-- Admin full access
CREATE POLICY "Admin full access on agent_registry" ON agent_registry
  FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Admin full access on agent_execution_log" ON agent_execution_log
  FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Admin full access on agent_daily_report" ON agent_daily_report
  FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Admin full access on agent_messages" ON agent_messages
  FOR ALL USING (auth.role() = 'service_role');

-- Authenticated users can read agents
CREATE POLICY "Read agents" ON agent_registry
  FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Read executions" ON agent_execution_log
  FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Read daily reports" ON agent_daily_report
  FOR SELECT USING (auth.role() = 'authenticated');
