// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

// Force clear cache if wrong key detected
if (typeof window !== 'undefined') {
  try {
    const parts = SUPABASE_PUBLISHABLE_KEY?.split('.');
    if (parts && parts.length === 3) {
      const payload = JSON.parse(atob(parts[1]));
      if (payload.iat !== 1760392191) {
        console.warn('⚠️ WRONG SUPABASE KEY CACHED - Clearing storage...');
        localStorage.clear();
        sessionStorage.clear();
        // Unregister service worker
        if ('serviceWorker' in navigator) {
          navigator.serviceWorker.getRegistrations().then(registrations => {
            for (const registration of registrations) {
              registration.unregister();
            }
          });
        }
        console.log('✅ Storage cleared. Please refresh page (Ctrl+Shift+R)');
      }
    }
  } catch (e) {
    console.error('Failed to check key:', e);
  }
}

// DEBUG: Check what key is being loaded
console.log('🔑 Supabase Client Debug:');
console.log('URL:', SUPABASE_URL);
console.log('Key exists:', !!SUPABASE_PUBLISHABLE_KEY);
console.log('Key length:', SUPABASE_PUBLISHABLE_KEY?.length);

// Decode JWT to check timestamp
if (SUPABASE_PUBLISHABLE_KEY) {
  try {
    const parts = SUPABASE_PUBLISHABLE_KEY.split('.');
    const payload = JSON.parse(atob(parts[1]));
    console.log('Key IAT:', payload.iat, payload.iat === 1760392191 ? '✅ CORRECT' : '❌ WRONG (cached)');
    console.log('Key EXP:', new Date(payload.exp * 1000).toLocaleDateString());
  } catch (e) {
    console.error('Failed to decode JWT:', e);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});